### ISSUE TITLE
Enable Theme switching

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#143]
## User story

1. As a facility manager
2. I want to be able to switch between dark and light theme
3. So that I can choose the Theme that suits me best

## Acceptance criteria

- [x] User is able to switch between dark and light Theme 

## Definition of done (DoD)

- [x] All acceptance criteria were met
- [x] Pipeline is building successfully
- [x] Unit/integration tests are passing
- [x] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [x] Developers agreed to release
- [x] Product owner approved features
- [x] Feature has been fully implemented

**Comment by Sungonogi** [comment]
Because I like to document: Lighttheme works perfectly by pressing the button in the bottom left. For this issue I just want to note that, while Alex of course did almost all the work, I supported for like 30minutes and helped with the decision where the button should be placed (so not on a separate page).

![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/2704cbf2-f3a8-4a23-8ab9-c3b7caced03f)
