### ISSUE TITLE
Provide feedback for Industry Partner on Siemens iX

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#207]
## User story

1. As a Siemens iX developer
2. I want / need useful feedback regarding the software
3. So that I can apply it and improve Siemens iX

## Acceptance criteria

- [ ] Detailed issues containing feedback from the dev team have been added in the Siemens iX repository

**Comment by Sungonogi** [comment]
I created a lot of issues which can be seen here:
https://github.com/siemens/ix/issues/1364
https://github.com/siemens/ix/issues/1365
https://github.com/siemens/ix/issues/1366
https://github.com/siemens/ix/issues/1367
https://github.com/siemens/ix/issues/1368

The text of them is:
### documentation of echarts
This is regarding the [echarts page](https://ix.siemens.io/docs/controls/charts/).

I know you only provide theming for the apache echarts. Still the documentation could be improved to make it easier for us to work with echarts.

For Angular: describe more detailed how to add `NgxEcharts` in your module file or add a link to such documentation. Also for standalone components tell us that we need to add `provideEcharts()` to our providers in `app.config.ts`.

Another thing you could add is an example with real time data. So explain how to use dates as timesteps on the x-axis and how the series items for lines on the y-axis should look. Using the echarts dataset for this would be nice too.

Again, of course that would be duplicate to some apache documentation but I think they did not make this very clear. So it would still be immensely helpful and make Siemens iX easier to use for everyone working with it.
### documentation of modals
This is regarding the [modal page](https://ix.siemens.io/docs/controls/modal/).

It would be nice in the Angular `modal-by-instance.ts` example to also show how to use the value from the modal. A simple example that sets a boolean `cancelled` to true or false depending on if the Modal was dismissed(`instance.onDismiss()`) or closed(`instance.onClose()`) would be enough.

### documentation of form validation
This is regarding the [validation page](https://ix.siemens.io/docs/controls/validation).

Currently this page only shows how to validate simple input fields. Very often that is not enough. It would be nice if it was also explained how to validate:
- A select field [\<ix-select\>](https://ix.siemens.io/docs/controls/select) to be required to pick one of the values
- A Date picker [\<ix-date-picker\>](https://ix.siemens.io/docs/controls/date-picker) to maybe have a value in the past/future or something else
- maybe consider also doing this for Date time picker or just time picker but that is not as important
- surely some other things I can't think of right now

### Common Questions Tab
Maybe this already exists somewhere. It would just be nice if these things show up if you use the search in the top right on the [siemens ix page](https://ix.siemens.io/docs/introduction)

1. Why is IntelliJ not recognizing the events emmited by the components?
   (Context: For me in IntelliJ all emmited events like ( backButtonClick), .... are marked as red because IntelliJ does not recognize them. They still work but it is very confusing for me and I thought it was because we made a mistake)
2. Is Siemens iX compatible with tailwind?
   Maybe this is obvious for you but just mentioning it once somewhere would be enough

### \<ix-card-list\> Show all

This is regarding the [\<ix-card-list\>](https://ix.siemens.io/docs/controls/card-list) .

I think it is very unintuitive that the "Show all ..." Button does not actually show you all of the cards on the same page but that it just emits an event and you have to redirect it to a new page.

I would suggest giving it the default behavior to just show all the cards.

In case you want to keep it like that I think it would be good to at least
- give us the option to show all the cards all the time and disable the "..."  (The option "suppressOverflowHandling" just hides the "..." but still does not show all cards)
- mention this behavior somewhere in the "\</\> Development" tab because it is not very clear to us devs. From my experience even if there is a ux person he will probably just say use "ix-card-list" but not necessarily read all the UX guidelines and miss this


### documentation problems

#### docu for standalone components
- includes `importProvidersFrom(IxModule.forRoot())` and `provideAnimations` on the install page
- includes `provideEcharts()` on the echarts page
- surely a lot of other positions

#### Link in this repo does not work
This regards the [CONTRIBUTING.md](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#table-of-contents) on this github repository

The link to  `documentation` in the following position does not work:

> - Read the [documentation](https://ix.siemens.io/version-dev/docs/getting-started/) carefully and find out if the functionality is already covered, maybe by an individual configuration.

**Comment by sn0wcat** [comment]
thanks @IngoSternberg !
