### ISSUE TITLE
State Management Login

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#230]
## User story

1. As a facility manager
2. I need a secure and efficient login system
3. So that my session is managed properly.
## Acceptance criteria

- [x] login page is default when opening the page (unless you logged in sometime in the last hour and did not log out in the end)
- [x] email: ingo.sternberg@fau.de and emails of other devs, all with password "siemens" work
- [x] if the credentials are correct a token is generated using cryptoJS and it is stored in the localstorage
- [x] after the login you can see everything and you are automatically logged in on other open tabs
- [x] the email in the top right is shown
- [x] you can log out by yourself or you are automatically logged out after 1h
- [x] you can not change the URL to just avoid the login
- [x] Design of the login page is adjusted

## Definition of done (DoD)

- [x] All acceptance criteria were met
- [x] Pipeline is building successfully
- [x] Unit/integration tests are passing
- [x] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [x] Developers agreed to release
- [x] Product owner approved features
- [x] Feature has been fully implemented

**Comment by Sungonogi** [comment]
I would also like to adjust the login page because right now I think it looks a bit cramped. Also the password forgotten and github login are not functional so I would like to remove them


![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/70c1eb89-b182-4849-8367-48cfbef50358)


I would like to make it somewhat similar to the normal [siemens login](https://login.siemens.com/u/login/identifier?state=hKFo2SBkSXZ5MHdJTVZKbTFQc3VDb3ZzU2k5UzBjcFhsOXVMSaFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIFcxeTdHRkd0QzB2eDkySWdXWFZCQmkzb3RaWTBzTHdno2NpZNkgeFNvN0R0SldtVWVXTTk3d2lHVk1SMzI5d1JxREc5cE8). But of course we need a password field and we don't need all the ones on the bottom. Also the colours will be a little different as they are the siemens-brand-dark/light colours and we only have the classic-dark/light available. So I'll see how close I can get to this:


![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/9c900d40-858c-41e4-afb5-cbcc0d358d1e)

**Comment by Sungonogi** [comment]
I changed how the login looks to this, which looks cleaner in my opinion
![grafik](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/7bbfa6ac-bb85-4a2c-8102-15f66d14b22e)

**Comment by Sungonogi** [comment]
I also thought about it more and I think it makes more sense to use an email adress instead of username. Like that we actually have an email adress to show for the #229 issue. The login works for any of the following email adresses using password "siemens":

alex.lorenz.1@gmx.de
lama.l.rajjo@fau.de
ingo.sternberg@fau.de
cecilia.betancourt@fau.de
jonas@mennicke.com
krugm03@gmail.com
nasirsharaz@gmail.com
patrick.m.schmidt@fau.de
saleb2k@gmail.com
d.schmidt@campus.tu-berlin.de
david_schmidt_privat@outlook.com
igor.milovanovic@siemens.com
buchner@group.riehle.org
riehle@group.riehle.org


I took them from the P1 Planning document and added a few more

**Comment by Sungonogi** [comment]
Btw if you want it to work you have to add the XD_SECRET_KEY to the .env file so you can ask me for it
