### ISSUE TITLE
Display information box for facilities in details page

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#77]
## User story

1. As a facility manager
2. I want / need to have an information box for facilities in details page
3. So that I can have a quick overview on important information for each facility

## Acceptance criteria

- [x] One more field is added to the details page in the form of a box
- [x] Information on facilities like location, etc are shown in the box for a quick overview.

## Definition of done (DoD)

- [x] All acceptance criteria were met
- [x] Pipeline is building successfully
- [x] Unit/integration tests are passing
- [x] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [x] Developers agreed to release
- [x] Product owner approved features
- [x] Feature has been fully implemented

## Dependencies

- Item [#54](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/54)

**Comment by Sungonogi** [comment]
I asked a question about the information of facilities we have and should show in the https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/27 issue

Since we will have more data to show for facilities in this issue, apart from the [basic information box](https://ix.siemens.io/docs/controls/card) on the details page it would also make sense to adjust the following things:

change what the user sees after opening the push card on the facilities overview
change what can be seen on the right side of the work orders form page as in this issue https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/81

this is also the reason why the size is 3 and not just 1/2

Since I probably have to spend some time on the frontend/backend connection this sprint I will leave this issue to @Hydraneut

**Comment by Sungonogi** [comment]
The box was added to the details page and it is working and you can even see the status of the facility in the corresponding colour
![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/126fafcb-59e6-4ec2-a30f-9bd87c2e95c3)

About the changes to the attributes of facilites:
They were left the same for now as we were still figuring out which attributes of facilities are stored in the backend
