### ISSUE TITLE
Service-like feature for FE pages of facilities to BE

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#82]
## User story

1. As a facility manager
2. I want to see the right facilities with their information from the backend
3. So that I can fetch and view up-to-date data regarding my facilities

## Acceptance criteria

- [x] the frontend calls (api/facilities) instead of (api/timeseries) to see the facilities. This also means we see one card per facility on the Facilities Overview Page and not 2/3 like before.
- [x] the facilities show their description and name from the backend instead of just their id.
- [x] both the facilities overview page and the facilities with issues page are adjusted
- [x] also on the details page we get the corresponding facility from the backend

## What is not inlcuded
Since this issue regards the facilities endpoint and not the timeseries endpoint it is not included to show Pump/ Environment data from the backend on the details page.

## DoD general criteria

- [x] Feature has been fully implemented
- [x] Feature has been merged into the mainline
- [x] All acceptance criteria were met
- [x] Product owner approved features
- [x] All tests are passing
- [x] Developers agreed to release

**Comment by IngoSternberg** [comment]
After @Persists explained us where the backend provides the data @Sabo2k and I implemented a service to fetch the data from the backend in the feat/xd-29-fetching-service branch. We will not merge this branch as we still need to figure out a good architecture to get the data in the frontend and not just have it in one service. It is still very useful to show that it works and how to get the data

**Comment by Sungonogi** [comment]
It is still on the feat/xd-82 branch because the backend part is also not already on develop but it is basically done. Now the facilities we can see make more sense. Before this we actually displayed 2 cards for every facility and did not get a lot of meaningful data (only assetId and propertysetname):

![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/c87375ed-0ce9-41cd-b3d6-c11fce254520)


Now we actually see the facilities with their name and description from the backend. We still get the id and use it tho.
![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/d0ab49c2-c973-4830-adf0-65fd20734d35)

**Comment by Sungonogi** [comment]
And now to the other part of this issue, which is basically #158. But it is also listed here that "the frontend of the facility details view displays data from the application's backend" and since this was the only branch where backend and frontend were ready for this stuff it should be ok. The facilities now show the actual pump data from the backend. The SIEMENS API only has meaningful values for 3 of the pumps right now tho


Playground-MSAgentPump (id: 8ccb6c1c6c464e5784410e5a1c8a8def)
![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/2f62b25f-1e31-4437-aec8-6a4295b14663)


PUMP-003 (id: bfcfbbdae35c4c9da77ef477b6612084)
![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/c61d8f48-b9f1-43f5-9e70-41d994ea1ed0)



PUMP-002 (id: ba9361db82f4411297bdd8494ecb040f)
![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/f5a718a5-4d91-4ccb-b02d-2ced54f11a2c)

**Comment by Sungonogi** [comment]
Since my comments must now be confusing, I adjusted the description so only the part with the facilities and not the part about pump data is included
