### ISSUE TITLE
Make charts show multiple data in Y axis

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#99]
## User story

1. As a facility manager
2. I want to have have the charts in the details page show multiple lines
3. So I can choose which data I would like to see

## Acceptance criteria

- [x] The charts on the details page show multiple lines on the y axis, for example flow, temperature, ...
- [x] Facility managers can choose which data he would like to see

## Definition of done (DoD)

- [x] All acceptance criteria were met
- [x] Pipeline is building successfully
- [x] Unit/integration tests are passing
- [x] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [x] Developers agreed to release
- [x] Product owner approved features
- [x] Feature has been fully implemented

**Comment by Sungonogi** [comment]
Just to document: You can see the multiple lines and if you click on them in the legend you can disable or enable them (and it will not show them anymore and possibly change the size of the chart if all other lines have smaller values)

![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/e43d9359-c5cc-450f-a68f-a15200ef7646)

Data is not from the backend yet because we first had to connect the backend to frontend in #102 but it will be done the next sprint
